-- BOOK CONTENT - START
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount)values ('1972-03-03', 1, 'superBook', 'Stone Harbor Emerging Markets Total Income Fund', '/assets/img/content/main/card.jpg','The window showed smudged fir',5399, 129, 30);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-01', -120, '9f95e587-b1e0-40d1-80ce-2edeefb60494', 'Christmas in July', '/assets/img/content/main/card.jpg', 'Construction Foreman', 4757, 3727, 79);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-08', 93, '67e5f83f-ced3-49ba-b408-828ffc8986e3', 'Offside', '/assets/img/content/main/card.jpg', 'Estimator', 7282, 3627, 86);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-08-03', -72, '0c0bd1f5-63c8-4814-bb32-4feb237d15dc', 'More About the Children of Noisy Village (a.k.a. More About the Children of Bullerby Village) (Mer om oss barn i Bullerbyn)', '/assets/img/content/main/card.jpg', 'Construction Foreman', 7125, 1426, 2);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-02-22', 121, '36d76c88-5d93-4bed-9be2-5fc924f43d85', 'Unfinished Business', '/assets/img/content/main/card.jpg', 'Construction Manager', 7999, 3515, 88);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-10-30', -121, '33fe1b48-22df-499a-a1e1-e6737230f35b', 'House II: The Second Story', '/assets/img/content/main/card.jpg', 'Supervisor', 7827, 438, 4);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-05', -87, 'b26489b9-0213-443e-b2d7-47052b86d32b', 'Mad Dog Coll', '/assets/img/content/main/card.jpg', 'Estimator', 7132, 697, 2);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-24', 10, '7c14ea4c-0718-4b2d-b131-e00ef9b994a1', 'Langoliers, The', '/assets/img/content/main/card.jpg', 'Construction Worker', 4631, 3046, 0);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-10-17', -101, '61961425-7afe-4da5-8e3b-5be20970c5a7', 'Fragile Trust: Plagiarism, Power, and Jayson Blair at the New York Times, A', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 4775, 3080, 96);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-30', -89, '112f0fbc-c7f3-4c71-93ce-2b595a2f7f07', 'Apollo 13: To the Edge and Back', '/assets/img/content/main/card.jpg', 'Surveyor', 5243, 2195, 9);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-11', 60, '71e66a1c-11ea-44b0-8ac4-19fccd0acd0e', 'Kiss Kiss Bang Bang', '/assets/img/content/main/card.jpg', 'Construction Manager', 5592, 356, 54);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-09-14', 93, '0122d22c-c47f-46a9-b87f-d922e6786174', 'World According to Sesame Street, The', '/assets/img/content/main/card.jpg', 'Supervisor', 4320, 3669, 79);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-18', 102, '43693705-2dd8-4c94-a3b1-c7711bcf6afa', 'Bag of Bones', '/assets/img/content/main/card.jpg', 'Project Manager', 5494, 251, 80);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-11', 10, '728e431e-11f8-46ad-8054-fbb73897aadf', 'Two Bits', '/assets/img/content/main/card.jpg', 'Project Manager', 5168, 1488, 46);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-12', 36, 'c32a7fdd-5467-4da8-9f7d-96ab2077fd93', 'Disco Dancer', '/assets/img/content/main/card.jpg', 'Architect', 5301, 1674, 55);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-11-13', 123, '00e811cd-e25b-4bda-8fcc-ecfd8f5e346f', 'Session 9', '/assets/img/content/main/card.jpg', 'Construction Manager', 6833, 2944, 7);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-08-05', 11, '33d516b8-dac0-4f9e-98ae-52c45f8f8f49', 'Tales That Witness Madness', '/assets/img/content/main/card.jpg', 'Subcontractor', 4922, 3484, 76);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-07-14', -125, '18f23bb6-d904-416e-82b5-300f286320ab', 'Gunfighter''s Moon', '/assets/img/content/main/card.jpg', 'Engineer', 4420, 2760, 37);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-06-23', -117, '041dad9e-e63d-448d-ad3c-b961920dc3d3', 'Norbit', '/assets/img/content/main/card.jpg', 'Estimator', 6723, 3818, 74);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-08-21', -56, 'ea149ebf-8fe0-445c-953f-3b483e00adc6', 'Lost Weekend, The', '/assets/img/content/main/card.jpg', 'Architect', 5418, 797, 16);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-01-05', 108, '1c327e8e-d672-4596-a409-0ce50e234b90', 'Phoebe in Wonderland', '/assets/img/content/main/card.jpg', 'Electrician', 5974, 3985, 76);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-17', -28, '8a3df0a4-46fc-4f35-a243-36c0f1822f60', 'How the Myth Was Made: A Study of Robert Flaherty''s Man of Aran', '/assets/img/content/main/card.jpg', 'Supervisor', 5610, 944, 79);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-07-22', 35, '86827116-3bb1-43b1-8708-9b90c545d01f', 'Brave New World', '/assets/img/content/main/card.jpg', 'Surveyor', 6285, 1651, 38);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-27', 4, '8ca4977b-9c46-4aeb-b77c-3438cfc64b33', 'Tenant, The (Locataire, Le)', '/assets/img/content/main/card.jpg', 'Project Manager', 5476, 560, 56);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-12-21', -122, '6fd334b6-78b0-40b3-8fdb-f57d5e5623b3', 'Keep the River on Your Right: A Modern Cannibal Tale', '/assets/img/content/main/card.jpg', 'Architect', 7199, 1171, 25);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-15', 34, 'b644a327-7630-421a-beca-14b4dc1bea9d', 'Hellraiser: Hellworld', '/assets/img/content/main/card.jpg', 'Engineer', 6995, 837, 13);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-07-15', -100, '9528398b-6fa1-4889-a3b4-02df818f6f4c', 'Ordinary Sinner', '/assets/img/content/main/card.jpg', 'Architect', 5085, 316, 21);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-09-04', -21, '77538ef5-21dd-45b7-97b8-2ac4f43b19e7', 'Magicians', '/assets/img/content/main/card.jpg', 'Surveyor', 4880, 3368, 73);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-08-27', 88, '8a2a7a1f-06df-4c90-afc5-ea8f68bde1c4', 'Future, The', '/assets/img/content/main/card.jpg', 'Supervisor', 6873, 1598, 89);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-23', 3, '58c726c4-cca5-407d-ae62-90770403553a', 'Forbidden', '/assets/img/content/main/card.jpg', 'Construction Foreman', 5148, 1156, 34);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-11-18', -71, 'ef28915d-1f8a-4d12-b71f-360f54e6467b', 'Invisible Invaders', '/assets/img/content/main/card.jpg', 'Electrician', 6496, 1169, 61);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-27', 70, 'fedb0f65-edb0-4a17-9ab6-338f45856930', 'Windows', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 5262, 2056, 9);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-19', 54, '11535526-ca6a-4a0e-b2d8-528c8b0c102d', 'Misfortunates, The (De helaasheid der dingen)', '/assets/img/content/main/card.jpg', 'Engineer', 7724, 3427, 3);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-11-05', -100, '5018d922-cc59-4c54-ae26-51c17c6722c7', 'Lumberjacking (Nuoruuteni savotat)', '/assets/img/content/main/card.jpg', 'Construction Manager', 7766, 659, 37);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-08-29', -68, '4fda3250-76ca-49bb-a765-5077c7e18e14', 'Joke, The (Zert)', '/assets/img/content/main/card.jpg', 'Construction Worker', 6707, 3085, 93);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-11-29', 20, '8cb6391e-23f4-4bad-a5b0-152327d682a3', 'Bad Men of Missouri', '/assets/img/content/main/card.jpg', 'Surveyor', 4521, 1481, 73);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-27', 59, '9538b97c-7fe3-44af-9809-36c74a34956d', 'Scandal', '/assets/img/content/main/card.jpg', 'Architect', 6137, 2152, 22);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-07-04', -26, '2f4ba7ea-5e95-453f-adc6-077a76b992bc', 'Racing with the Moon', '/assets/img/content/main/card.jpg', 'Surveyor', 4925, 3880, 92);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-23', 28, '25893e99-6c88-46ac-b24a-6446a6cba3a6', 'Behind Enemy Lines: Colombia (Behind Enemy Lines 3: Ghost Watch)', '/assets/img/content/main/card.jpg', 'Subcontractor', 4517, 1396, 68);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-01', 0, '7570601b-804a-404d-bc27-8a50d325d868', 'Book of Love', '/assets/img/content/main/card.jpg', 'Project Manager', 6275, 2005, 31);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-01-29', 28, '0b78cc7b-4ef2-4dcc-b157-b338b0972d14', 'Infernal Affairs 2 (Mou gaan dou II)', '/assets/img/content/main/card.jpg', 'Architect', 6066, 2594, 5);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-12', -83, '56c58505-2d43-46b3-8b53-efe2aad6775e', 'Bitch Slap', '/assets/img/content/main/card.jpg', 'Project Manager', 7048, 2937, 38);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-20', 78, '082b8474-29fe-4ccd-9e9f-f08e236eda5f', 'Fourth State, The (Die vierte Macht)', '/assets/img/content/main/card.jpg', 'Architect', 4971, 2279, 60);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-06-01', -71, '19c4ce03-cd9e-4653-8343-b92773323288', 'The Legend of Sarila', '/assets/img/content/main/card.jpg', 'Surveyor', 7747, 1705, 21);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-01', 41, '896e0469-2433-4875-b805-fc2e13a106b0', 'Racket, The', '/assets/img/content/main/card.jpg', 'Electrician', 4100, 1913, 50);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-23', 72, 'af2402fc-fc71-4a31-aee2-d0f8f7134999', 'People of the Wind', '/assets/img/content/main/card.jpg', 'Construction Manager', 7882, 2517, 27);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-12-27', -106, '217f55ee-7fd8-436f-a45e-a99a139c52a1', 'The Adventures of Hercules', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 7779, 1352, 73);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-02-16', 56, 'f7e52e30-45f3-4702-bbd6-4e1824b5fedf', 'Lovely to Look At', '/assets/img/content/main/card.jpg', 'Subcontractor', 6338, 3328, 36);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-08', -80, 'ed2e7d4d-b770-410e-86c6-e67b671d490d', 'Saw II', '/assets/img/content/main/card.jpg', 'Estimator', 5594, 348, 24);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-30', -47, '75af918f-8b67-4c85-a2a9-1dd06d4fa564', 'Italian for Beginners (Italiensk for begyndere)', '/assets/img/content/main/card.jpg', 'Construction Manager', 5635, 2822, 73);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-09-20', 82, 'e0fd85c2-fedb-4569-b823-6774f41e708c', 'Plan 9 from Outer Space', '/assets/img/content/main/card.jpg', 'Supervisor', 7452, 2515, 76);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-31', -113, '6b880850-66e8-4d4a-8190-db0c33ff425d', 'American Raspberry (Prime Time) (Funny America)', '/assets/img/content/main/card.jpg', 'Subcontractor', 5334, 3800, 11);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-01-05', 25, 'b1ce2668-3636-4090-b184-f75259f8f085', 'Winning Team, The', '/assets/img/content/main/card.jpg', 'Electrician', 5628, 3116, 10);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-06-29', 58, 'f63556ce-f593-46fc-9ac0-d7f6c7a822f7', 'Night at the Museum: Battle of the Smithsonian', '/assets/img/content/main/card.jpg', 'Construction Worker', 7247, 2518, 19);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-29', -66, 'b9946f20-b404-4359-906b-8ba45f2bf863', 'Spring', '/assets/img/content/main/card.jpg', 'Engineer', 7846, 3353, 60);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-11-24', 75, 'f65d1dde-c31f-4247-8e02-1bc56b8441c5', 'Dandelion', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 5669, 1987, 38);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-10-23', -88, 'ffe76f36-3c75-4ed6-8484-5a3a483aa5bd', 'Rapture-Palooza', '/assets/img/content/main/card.jpg', 'Construction Manager', 7820, 668, 16);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-10-23', 82, '6772bc90-5bf0-4e91-b1a8-9d76bd05ad03', 'Thirteen Days', '/assets/img/content/main/card.jpg', 'Construction Worker', 7431, 1615, 56);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-08-09', 119, '834a9a85-d0bd-484f-adda-e2f08a6e56ab', 'Keeper of Lost Causes, The (Kvinden i buret)', '/assets/img/content/main/card.jpg', 'Surveyor', 5232, 3878, 48);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-02-22', -15, '73f71b30-f4ea-45c6-81f4-8c8b3ae86767', 'Evil Dead', '/assets/img/content/main/card.jpg', 'Architect', 5560, 3126, 79);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-19', -78, 'af4a59d8-de30-4529-a559-005becc89d7d', 'Allegheny Uprising', '/assets/img/content/main/card.jpg', 'Supervisor', 6130, 1111, 16);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-20', 9, 'ecd6725b-705b-432f-b4c6-d54a84310256', 'Cassandra''s Dream', '/assets/img/content/main/card.jpg', 'Electrician', 5850, 467, 81);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-11-25', 78, '5cf32a4e-4e17-4ea2-b80f-208c728f65e4', 'Top Banana', '/assets/img/content/main/card.jpg', 'Project Manager', 5076, 3168, 96);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-09-02', -3, 'd6492011-e937-47da-afd4-c5db24a27b6f', 'Guru, The', '/assets/img/content/main/card.jpg', 'Construction Worker', 5259, 2439, 82);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-22', -105, 'f09db7e7-1770-4f92-b083-9cd4953b71ef', 'Fahrenhype 9/11', '/assets/img/content/main/card.jpg', 'Architect', 4031, 3446, 16);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-08-21', -8, '1da1993d-6e18-46f1-b7b1-d0d2efdb1a7f', 'Human Centipede II (Full Sequence), The', '/assets/img/content/main/card.jpg', 'Construction Manager', 5807, 1595, 35);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-13', -43, '391c0e8a-1e08-4972-bfce-d643423f8b66', 'Tomcats', '/assets/img/content/main/card.jpg', 'Supervisor', 6571, 3510, 6);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-24', -39, 'adc2071f-c8cb-4fb8-a2d7-6185e0490f62', 'The Fox and the Hound 2', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 6668, 3398, 23);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-11-05', -69, 'f64dbd36-c7fd-43f5-a65b-ad06dca0d8d7', 'Spider', '/assets/img/content/main/card.jpg', 'Architect', 7659, 1366, 56);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-02-08', 92, '0ed93904-f15f-49a7-8ea3-6e2acd1640c9', 'Holy Guests (Ha-Ushpizin)', '/assets/img/content/main/card.jpg', 'Surveyor', 6409, 2007, 23);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-06-02', 94, 'd5543e01-17c1-4eb3-87d4-1acc30f3341a', 'Nemesis 3: Time Lapse', '/assets/img/content/main/card.jpg', 'Estimator', 5287, 2700, 86);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-10-15', 13, '33652e82-d505-495d-bc9e-174a64fd043c', 'Beach Blanket Bingo', '/assets/img/content/main/card.jpg', 'Architect', 6296, 3350, 1);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-03', -44, 'ff97be26-f5a9-494d-8810-2b3a31f60160', 'Road to Hong Kong, The', '/assets/img/content/main/card.jpg', 'Supervisor', 7887, 2974, 94);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-23', -126, 'ae45292a-7a55-4c1e-8c48-f8026118bd46', 'Inhuman Resources (Redd Inc.)', '/assets/img/content/main/card.jpg', 'Estimator', 4013, 3646, 73);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-20', 18, 'fc940124-55da-495d-8847-809737d1cb6c', 'The Challenge', '/assets/img/content/main/card.jpg', 'Subcontractor', 4472, 1607, 68);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-07-07', -103, '55efb7d1-e690-4768-ac5a-f370c0173c4b', 'All the Way Boys (Più forte, ragazzi!)', '/assets/img/content/main/card.jpg', 'Estimator', 7004, 3041, 68);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-20', -25, 'ae2b429f-8e6b-4acf-ba6a-6545bfdc2feb', 'C.O.G.', '/assets/img/content/main/card.jpg', 'Engineer', 4683, 862, 69);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-01-04', 81, 'a0343c42-c77f-458e-b31f-a2495789e41b', 'Wild Oranges', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 5592, 2756, 87);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-06-11', -118, 'c5eec414-40af-41e9-8ad6-8f4d4170c467', 'Monkey Shines', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 6087, 1443, 86);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-06-26', 60, '9e0e9c2f-5d6c-4974-bb62-ab91be2fec12', 'Night of the Generals, The', '/assets/img/content/main/card.jpg', 'Engineer', 7138, 1458, 26);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-07-30', 111, '597e9511-f867-47c8-b8b9-d162736ca849', 'Outcast of the Islands', '/assets/img/content/main/card.jpg', 'Supervisor', 6138, 1812, 10);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-28', -34, 'e7fbaf1e-01fc-4621-a7c7-6d405e7816e2', 'Think Fast, Mr. Moto', '/assets/img/content/main/card.jpg', 'Electrician', 7754, 3032, 95);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-12-21', 127, '6628d790-95f9-4ecf-bdc4-ead8646a5751', 'Siddhartha', '/assets/img/content/main/card.jpg', 'Surveyor', 5637, 397, 28);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-07-06', -85, 'a492d765-4e06-4f35-b53c-00ea751887d0', '[REC]²', '/assets/img/content/main/card.jpg', 'Estimator', 5506, 2399, 27);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-08-11', 103, '770c8787-1d30-44b6-a723-17bda5cb7237', 'Den sommeren jeg fylte 15', '/assets/img/content/main/card.jpg', 'Engineer', 7543, 652, 5);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-30', -100, 'cde97f98-c5e0-4184-817a-cfdd53a2f487', 'The Left Handed Gun', '/assets/img/content/main/card.jpg', 'Construction Manager', 7805, 2167, 88);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-06-19', 36, '8f941bd3-234f-4320-b1e8-e86bfe6066a1', 'Street Fighter II: The Animated Movie (Sutorîto Faitâ II gekijô-ban)', '/assets/img/content/main/card.jpg', 'Electrician', 7809, 1722, 5);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-06-20', -28, 'e526d388-56a6-42ce-8170-ace91cfcc208', 'Ain''t Them Bodies Saints', '/assets/img/content/main/card.jpg', 'Construction Manager', 6398, 568, 14);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-02', 2, 'baeab89d-0283-419a-bf54-9fd37234aa1e', 'Shooting Gallery', '/assets/img/content/main/card.jpg', 'Construction Manager', 7224, 1612, 47);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-09-27', 125, '473ea7ad-9621-4c32-adaf-4ae1273ddeaa', 'Carmina or Blow Up (Carmina o revienta)', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 4601, 2449, 64);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-06-02', -67, '042d0e12-37b1-4e58-b9e6-b7a65e4e554f', 'Tokyo.Sora', '/assets/img/content/main/card.jpg', 'Subcontractor', 4181, 629, 56);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-05', 112, '93d5f07e-c679-4c35-bbed-61bdfcb9deca', 'Innocent Affair, An (Don''t Trust Your Husband) (Under Suspicion)', '/assets/img/content/main/card.jpg', 'Electrician', 5697, 2419, 41);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-03-09', -66, '92d044a9-e5f6-489f-ae97-df7a945ac2bc', 'Rock Star', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 7255, 2953, 24);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-12-13', 16, 'c637d6cc-4ea5-4fca-827b-19687edad2d8', 'Steamboat Bill, Jr.', '/assets/img/content/main/card.jpg', 'Construction Expeditor', 6420, 110, 19);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-06-19', -26, '35ef8b56-2015-41d0-8121-ff913bcf8ca8', 'Natural Born Killers', '/assets/img/content/main/card.jpg', 'Construction Worker', 5404, 1494, 67);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-04-11', -107, 'dbbb171c-3ce9-4079-8bde-806baefd8fa8', 'Battling Butler', '/assets/img/content/main/card.jpg', 'Architect', 5397, 1107, 77);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-08-05', 51, 'b2c12ecb-413c-4202-8948-b9cef466854c', 'Getting Back to Abnormal', '/assets/img/content/main/card.jpg', 'Electrician', 6349, 587, 21);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-05-04', 87, 'f613da79-53e7-4108-b6da-5417343b3403', 'Dead of the Nite', '/assets/img/content/main/card.jpg', 'Construction Foreman', 5939, 893, 96);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2021-09-20', 68, 'ee000630-f738-4bb6-818d-2827ec2222e5', 'Dead Awake', '/assets/img/content/main/card.jpg', 'Estimator', 6145, 1292, 55);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-01-18', 20, 'a552e42d-7796-4209-bcbd-8c542ec8cdd7', 'House of Bamboo', '/assets/img/content/main/card.jpg', 'Construction Worker', 6595, 1209, 99);
insert into book (pub_date, is_bestseller, slug, title, image_, description, priceOld, price, discount) values ('2022-06-06', -79, '74f02e56-4537-4f86-bf05-aadf6fb6a55f', 'Men at Work', '/assets/img/content/main/card.jpg', 'Supervisor', 7421, 3580, 74);
-- BOOK CONTENT - FINISH
-- AUTHOR CONTENT - START
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '15j2yCD2y6bFmVRMtNtGo4b6ryDqPN9BHV', 'Basilio Batsford', 'Otogenic pain');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1F6u1L94kt6zyvCNTp4Y3Az7oFGsRFAJaF', 'Gertruda Fulop', 'Adv eff blood agent NOS');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '15gUjSgZ5v1Vk7ZpDGk2v1Nn1as9m1PtQ7', 'Clara Attridge', 'React-inter joint prost');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '142pnJkj3UiK6pPH5WCkhrDZPjGsJYZMkM', 'Katy Cadding', 'Viral meningitis NOS');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '152sjYJ36bjQEzfLrGtrGimRC4VSbw9qej', 'Giuseppe Thaine', 'Grand mal status');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1F9phgQ5HYxJAMdAD3pytaQsh8qREBDKXY', 'Raimund Bichener', '50-59% bdy brn/20-29% 3d');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '19sVaWErjcrw38YAphVbwQcoFGyfBexVij', 'Tonie Paolone', 'Caregiving NEC');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '16mzVonS6SuayqiKuBDGqRA9tFptayhEk4', 'Clevie Pedrollo', 'Pulm alveolar microlith');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '12rTQSTHHYoaNuTWZ1dSth6J9koQ51RMk6', 'Rhianon Whild', 'Fam hx MEN syndrome');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1FA9t6cqpRRT3QpVkSqauouHWSxFX9JvCs', 'Margie Milley', 'Fetopelv disprop-unspec');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1FuJfNywb6MBNdRQXtTWoDzQjZCbGgaKAf', 'Lammond Koeppke', 'Liveborn NOS-hosp w/o cs');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1AaPm9JgW4XzkokMdGDdXdVWqgxWfgNYyy', 'Martelle Duigan', 'Bsl cel skn face NEC/NOS');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1FvLcbmC4jAv1aKWFtktiscncstRy2kuxg', 'Curran Lindenman', 'Amebic skin ulceration');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1MpCgf7b2K3ugxWGhryRNfgGeNcSYqBLyy', 'Andie Spinney', 'Tibial coll lig bursitis');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '13cVpuH7M1knLSDhJuQWzBJCNqXx6DLvoH', 'Nanete Crumly', 'Jt derangment NEC-pelvis');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1F66RQAdGFS9uVjkfGKXp6NVKNxm7DTPnm', 'Rees Belch', 'Opn brain inj w/o coma');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1Kr5gqKWy1u5u2obEKqtGXWN3aW5RsDsuJ', 'Carolyne Figurski', 'Joint pain-unspec');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1C3AbRQFv2CV6Gri7uei4S1kBW4b4qcxrQ', 'Bevon Grgic', 'Poisoning-system agt NEC');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1Dg1CqTyTBZE6vG8GdD1t7XMJ5SaAR5EzQ', 'Erik Presnail', 'Fracture patella-open');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1HT58gDmscHjUSGq5n2qm4n5Me2SSDGr93', 'Laurie Deroche', 'Injury accessory nerve');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1DGVVqeRHK2zDGdRNtsxhwz259zBTpqgn4', 'Shoshanna Goneau', 'Flu dt nvl A vrs w pneu');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1G7hatMmzxTvhh5sJz7n4xBSCoY7zPgxKh', 'Shelley Roggers', 'Valgus deformity wrist');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1MaE753zhBDiE5j8BpPp1amj1aJsCnrmgX', 'Tamar Dreger', 'Dosag fail-shock therapy');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1ET2pVggyKr9WvqUhmZnFYz6xpwc2mgTpN', 'Pauli Hatchett', 'Cortex lacerat-prol coma');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1NUp6PcbtMcUWoRMPPhhRKiDsdDNehFjdb', 'Kent Perchard', 'Recur preg loss-unspec');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '13uBTV7qN9vPSu1YxJoe5QRj3dpt45zJmj', 'Forbes O''Doireidh', 'Placental polyp-unspec');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '13G6F4ZE7kEmtE1pHy9hQx8mknym2fdH1h', 'Cornelia Morffew', 'Constipation NOS');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '17dSdihbUoh9Zi7ryNzfmBfoHFBcig1Ehp', 'Addia Bysshe', 'Bipol I currnt mixed-mod');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '123iFHJieATQRdVfkAy2RTh5sTNPLmnMNp', 'Mercy Barnet', 'Fx clavicle NOS-closed');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1ENWAZr5Q3oxb8HvcmCrsUi3CydHiTHPC1', 'Pen Crush', 'Nasal bone fx-open');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '12CgpMeHm8KfAtNHB8vMkVUtfox9e9C3gR', 'Lauretta Berger', 'Sensor prob w neck/trunk');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1KJGJeUc8RyeC2XxcWpCML4kxA7BEEpPJA', 'Ann-marie Carver', 'Heat exhaust-anhydrotic');
insert into author (photo, slug, name, description) values ('/assets/img/content/main/author.jpg', '1KNGTKEmZTZRPNDg53JRyBDRZkPbJZhT1L', 'Niel Phizakarley', 'Hypopotassemia');

-- AUTHOR CONTENT - FINISH

-- book2author CONTENT - START
insert into book2author (book_id, author_id, sort_index) values (1, 12, 1);
insert into book2author (book_id, author_id, sort_index) values (1, 29, 2);
insert into book2author (book_id, author_id, sort_index) values (1, 5, 3);
insert into book2author (book_id, author_id, sort_index) values (2, 24, 1);
insert into book2author (book_id, author_id, sort_index) values (2, 21, 2);
insert into book2author (book_id, author_id, sort_index) values (3, 19, 1);
insert into book2author (book_id, author_id, sort_index) values (3, 18, 2);
insert into book2author (book_id, author_id, sort_index) values (3, 4, 3);
insert into book2author (book_id, author_id, sort_index) values (4, 27, 1);
insert into book2author (book_id, author_id, sort_index) values (4, 8, 2);
insert into book2author (book_id, author_id, sort_index) values (5, 2, 1);
insert into book2author (book_id, author_id, sort_index) values (5, 11, 2);
insert into book2author (book_id, author_id, sort_index) values (5, 23, 3);
insert into book2author (book_id, author_id, sort_index) values (6, 17, 1);
insert into book2author (book_id, author_id, sort_index) values (6, 15, 2);
insert into book2author (book_id, author_id, sort_index) values (7, 3, 1);
insert into book2author (book_id, author_id, sort_index) values (7, 17, 2);
insert into book2author (book_id, author_id, sort_index) values (7, 32, 3);
insert into book2author (book_id, author_id, sort_index) values (8, 31, 1);
insert into book2author (book_id, author_id, sort_index) values (8, 24, 2);
insert into book2author (book_id, author_id, sort_index) values (9, 20, 1);
insert into book2author (book_id, author_id, sort_index) values (9, 14, 2);
insert into book2author (book_id, author_id, sort_index) values (9, 8, 3);
insert into book2author (book_id, author_id, sort_index) values (10, 17, 1);
insert into book2author (book_id, author_id, sort_index) values (10, 30, 2);
insert into book2author (book_id, author_id, sort_index) values (11, 16, 1);
insert into book2author (book_id, author_id, sort_index) values (11, 15, 2);
insert into book2author (book_id, author_id, sort_index) values (11, 2, 3);
insert into book2author (book_id, author_id, sort_index) values (12, 10, 1);
insert into book2author (book_id, author_id, sort_index) values (12, 6, 2);
insert into book2author (book_id, author_id, sort_index) values (13, 11, 1);
insert into book2author (book_id, author_id, sort_index) values (13, 5, 2);
insert into book2author (book_id, author_id, sort_index) values (13, 27, 3);
insert into book2author (book_id, author_id, sort_index) values (14, 4, 1);
insert into book2author (book_id, author_id, sort_index) values (14, 21, 2);
insert into book2author (book_id, author_id, sort_index) values (15, 24, 1);
insert into book2author (book_id, author_id, sort_index) values (15, 1, 2);
insert into book2author (book_id, author_id, sort_index) values (15, 12, 3);
insert into book2author (book_id, author_id, sort_index) values (16, 13, 1);
insert into book2author (book_id, author_id, sort_index) values (16, 9, 2);
insert into book2author (book_id, author_id, sort_index) values (17, 14, 1);
insert into book2author (book_id, author_id, sort_index) values (17, 13, 2);
insert into book2author (book_id, author_id, sort_index) values (17, 10, 3);
insert into book2author (book_id, author_id, sort_index) values (18, 7, 1);
insert into book2author (book_id, author_id, sort_index) values (18, 17, 2);
insert into book2author (book_id, author_id, sort_index) values (19, 22, 1);
insert into book2author (book_id, author_id, sort_index) values (19, 29, 2);
insert into book2author (book_id, author_id, sort_index) values (19, 17, 3);
insert into book2author (book_id, author_id, sort_index) values (20, 18, 1);
insert into book2author (book_id, author_id, sort_index) values (20, 14, 2);
insert into book2author (book_id, author_id, sort_index) values (21, 9, 1);
insert into book2author (book_id, author_id, sort_index) values (21, 6, 2);
insert into book2author (book_id, author_id, sort_index) values (21, 3, 3);
insert into book2author (book_id, author_id, sort_index) values (22, 24, 1);
insert into book2author (book_id, author_id, sort_index) values (22, 4, 2);
insert into book2author (book_id, author_id, sort_index) values (23, 10, 1);
insert into book2author (book_id, author_id, sort_index) values (23, 15, 2);
insert into book2author (book_id, author_id, sort_index) values (23, 3, 3);
insert into book2author (book_id, author_id, sort_index) values (24, 5, 1);
insert into book2author (book_id, author_id, sort_index) values (24, 21, 2);
insert into book2author (book_id, author_id, sort_index) values (25, 31, 1);
insert into book2author (book_id, author_id, sort_index) values (25, 26, 2);
insert into book2author (book_id, author_id, sort_index) values (25, 6, 3);
insert into book2author (book_id, author_id, sort_index) values (26, 31, 1);
insert into book2author (book_id, author_id, sort_index) values (26, 15, 2);
insert into book2author (book_id, author_id, sort_index) values (27, 5, 1);
insert into book2author (book_id, author_id, sort_index) values (27, 19, 2);
insert into book2author (book_id, author_id, sort_index) values (27, 28, 3);
insert into book2author (book_id, author_id, sort_index) values (28, 10, 1);
insert into book2author (book_id, author_id, sort_index) values (28, 17, 2);
insert into book2author (book_id, author_id, sort_index) values (29, 1, 1);
insert into book2author (book_id, author_id, sort_index) values (29, 6, 2);
insert into book2author (book_id, author_id, sort_index) values (29, 13, 3);
insert into book2author (book_id, author_id, sort_index) values (30, 16, 1);
insert into book2author (book_id, author_id, sort_index) values (30, 32, 2);
insert into book2author (book_id, author_id, sort_index) values (31, 17, 1);
insert into book2author (book_id, author_id, sort_index) values (31, 21, 2);
insert into book2author (book_id, author_id, sort_index) values (31, 31, 3);
insert into book2author (book_id, author_id, sort_index) values (32, 12, 1);
insert into book2author (book_id, author_id, sort_index) values (32, 4, 2);
insert into book2author (book_id, author_id, sort_index) values (33, 21, 1);
insert into book2author (book_id, author_id, sort_index) values (33, 5, 2);
insert into book2author (book_id, author_id, sort_index) values (33, 6, 3);
insert into book2author (book_id, author_id, sort_index) values (34, 23, 1);
insert into book2author (book_id, author_id, sort_index) values (34, 21, 2);
insert into book2author (book_id, author_id, sort_index) values (35, 29, 1);
insert into book2author (book_id, author_id, sort_index) values (35, 21, 2);
insert into book2author (book_id, author_id, sort_index) values (35, 15, 3);
insert into book2author (book_id, author_id, sort_index) values (36, 13, 1);
insert into book2author (book_id, author_id, sort_index) values (36, 2, 2);
insert into book2author (book_id, author_id, sort_index) values (37, 27, 1);
insert into book2author (book_id, author_id, sort_index) values (37, 28, 2);
insert into book2author (book_id, author_id, sort_index) values (37, 22, 3);
insert into book2author (book_id, author_id, sort_index) values (38, 23, 1);
insert into book2author (book_id, author_id, sort_index) values (38, 2, 2);
insert into book2author (book_id, author_id, sort_index) values (39, 29, 1);
insert into book2author (book_id, author_id, sort_index) values (39, 5, 2);
insert into book2author (book_id, author_id, sort_index) values (39, 3, 3);
insert into book2author (book_id, author_id, sort_index) values (40, 32, 1);
insert into book2author (book_id, author_id, sort_index) values (40, 23, 2);
insert into book2author (book_id, author_id, sort_index) values (41, 16, 1);
insert into book2author (book_id, author_id, sort_index) values (41, 31, 2);
insert into book2author (book_id, author_id, sort_index) values (41, 25, 3);
insert into book2author (book_id, author_id, sort_index) values (42, 26, 1);
insert into book2author (book_id, author_id, sort_index) values (42, 28, 2);
insert into book2author (book_id, author_id, sort_index) values (43, 33, 1);
insert into book2author (book_id, author_id, sort_index) values (43, 27, 2);
insert into book2author (book_id, author_id, sort_index) values (43, 15, 3);
insert into book2author (book_id, author_id, sort_index) values (44, 6, 1);
insert into book2author (book_id, author_id, sort_index) values (44, 14, 2);
insert into book2author (book_id, author_id, sort_index) values (45, 27, 1);
insert into book2author (book_id, author_id, sort_index) values (45, 3, 2);
insert into book2author (book_id, author_id, sort_index) values (45, 3, 3);
insert into book2author (book_id, author_id, sort_index) values (46, 15, 1);
insert into book2author (book_id, author_id, sort_index) values (46, 10, 2);
insert into book2author (book_id, author_id, sort_index) values (47, 32, 1);
insert into book2author (book_id, author_id, sort_index) values (47, 25, 2);
insert into book2author (book_id, author_id, sort_index) values (47, 4, 3);
insert into book2author (book_id, author_id, sort_index) values (48, 27, 1);
insert into book2author (book_id, author_id, sort_index) values (48, 2, 2);
insert into book2author (book_id, author_id, sort_index) values (49, 6, 1);
insert into book2author (book_id, author_id, sort_index) values (49, 15, 2);
insert into book2author (book_id, author_id, sort_index) values (49, 6, 3);
insert into book2author (book_id, author_id, sort_index) values (50, 9, 1);
insert into book2author (book_id, author_id, sort_index) values (50, 3, 2);
insert into book2author (book_id, author_id, sort_index) values (51, 13, 1);
insert into book2author (book_id, author_id, sort_index) values (51, 32, 2);
insert into book2author (book_id, author_id, sort_index) values (51, 18, 3);
insert into book2author (book_id, author_id, sort_index) values (52, 29, 1);
insert into book2author (book_id, author_id, sort_index) values (52, 7, 2);
insert into book2author (book_id, author_id, sort_index) values (53, 20, 1);
insert into book2author (book_id, author_id, sort_index) values (53, 23, 2);
insert into book2author (book_id, author_id, sort_index) values (53, 6, 3);
insert into book2author (book_id, author_id, sort_index) values (54, 25, 1);
insert into book2author (book_id, author_id, sort_index) values (54, 16, 2);
insert into book2author (book_id, author_id, sort_index) values (55, 3, 1);
insert into book2author (book_id, author_id, sort_index) values (55, 5, 2);
insert into book2author (book_id, author_id, sort_index) values (55, 2, 3);
insert into book2author (book_id, author_id, sort_index) values (56, 1, 1);
insert into book2author (book_id, author_id, sort_index) values (56, 16, 2);
insert into book2author (book_id, author_id, sort_index) values (57, 13, 1);
insert into book2author (book_id, author_id, sort_index) values (57, 16, 2);
insert into book2author (book_id, author_id, sort_index) values (57, 32, 3);
insert into book2author (book_id, author_id, sort_index) values (58, 6, 1);
insert into book2author (book_id, author_id, sort_index) values (58, 25, 2);
insert into book2author (book_id, author_id, sort_index) values (59, 7, 1);
insert into book2author (book_id, author_id, sort_index) values (59, 7, 2);
insert into book2author (book_id, author_id, sort_index) values (59, 17, 3);
insert into book2author (book_id, author_id, sort_index) values (60, 10, 1);
insert into book2author (book_id, author_id, sort_index) values (60, 4, 2);
insert into book2author (book_id, author_id, sort_index) values (61, 3, 1);
insert into book2author (book_id, author_id, sort_index) values (61, 3, 2);
insert into book2author (book_id, author_id, sort_index) values (61, 13, 3);
insert into book2author (book_id, author_id, sort_index) values (62, 8, 1);
insert into book2author (book_id, author_id, sort_index) values (62, 19, 2);
insert into book2author (book_id, author_id, sort_index) values (63, 29, 1);
insert into book2author (book_id, author_id, sort_index) values (63, 26, 2);
insert into book2author (book_id, author_id, sort_index) values (63, 18, 3);
insert into book2author (book_id, author_id, sort_index) values (64, 16, 1);
insert into book2author (book_id, author_id, sort_index) values (64, 26, 2);
insert into book2author (book_id, author_id, sort_index) values (65, 10, 1);
insert into book2author (book_id, author_id, sort_index) values (65, 17, 2);
insert into book2author (book_id, author_id, sort_index) values (65, 22, 3);
insert into book2author (book_id, author_id, sort_index) values (66, 13, 1);
insert into book2author (book_id, author_id, sort_index) values (66, 3, 2);
insert into book2author (book_id, author_id, sort_index) values (67, 27, 1);
insert into book2author (book_id, author_id, sort_index) values (67, 22, 2);
insert into book2author (book_id, author_id, sort_index) values (67, 17, 3);
insert into book2author (book_id, author_id, sort_index) values (68, 27, 1);
insert into book2author (book_id, author_id, sort_index) values (68, 9, 2);
insert into book2author (book_id, author_id, sort_index) values (69, 26, 1);
insert into book2author (book_id, author_id, sort_index) values (69, 6, 2);
insert into book2author (book_id, author_id, sort_index) values (69, 2, 3);
insert into book2author (book_id, author_id, sort_index) values (70, 28, 1);
insert into book2author (book_id, author_id, sort_index) values (70, 20, 2);
insert into book2author (book_id, author_id, sort_index) values (71, 7, 1);
insert into book2author (book_id, author_id, sort_index) values (71, 1, 2);
insert into book2author (book_id, author_id, sort_index) values (71, 10, 3);
insert into book2author (book_id, author_id, sort_index) values (72, 23, 1);
insert into book2author (book_id, author_id, sort_index) values (72, 1, 2);
insert into book2author (book_id, author_id, sort_index) values (73, 7, 1);
insert into book2author (book_id, author_id, sort_index) values (73, 27, 2);
insert into book2author (book_id, author_id, sort_index) values (73, 20, 3);
insert into book2author (book_id, author_id, sort_index) values (74, 1, 1);
insert into book2author (book_id, author_id, sort_index) values (74, 11, 2);
insert into book2author (book_id, author_id, sort_index) values (75, 24, 1);
insert into book2author (book_id, author_id, sort_index) values (75, 22, 2);
insert into book2author (book_id, author_id, sort_index) values (75, 5, 3);
insert into book2author (book_id, author_id, sort_index) values (76, 26, 1);
insert into book2author (book_id, author_id, sort_index) values (76, 21, 2);
insert into book2author (book_id, author_id, sort_index) values (77, 12, 1);
insert into book2author (book_id, author_id, sort_index) values (77, 31, 2);
insert into book2author (book_id, author_id, sort_index) values (77, 17, 3);
insert into book2author (book_id, author_id, sort_index) values (78, 27, 1);
insert into book2author (book_id, author_id, sort_index) values (78, 32, 2);
insert into book2author (book_id, author_id, sort_index) values (79, 22, 1);
insert into book2author (book_id, author_id, sort_index) values (79, 32, 2);
insert into book2author (book_id, author_id, sort_index) values (79, 14, 3);
insert into book2author (book_id, author_id, sort_index) values (80, 1, 1);
insert into book2author (book_id, author_id, sort_index) values (80, 1, 2);
insert into book2author (book_id, author_id, sort_index) values (81, 26, 1);
insert into book2author (book_id, author_id, sort_index) values (81, 23, 2);
insert into book2author (book_id, author_id, sort_index) values (81, 23, 3);
insert into book2author (book_id, author_id, sort_index) values (82, 12, 1);
insert into book2author (book_id, author_id, sort_index) values (82, 26, 2);
insert into book2author (book_id, author_id, sort_index) values (83, 5, 1);
insert into book2author (book_id, author_id, sort_index) values (83, 12, 2);
insert into book2author (book_id, author_id, sort_index) values (83, 13, 3);
insert into book2author (book_id, author_id, sort_index) values (84, 1, 1);
insert into book2author (book_id, author_id, sort_index) values (84, 25, 2);
insert into book2author (book_id, author_id, sort_index) values (85, 10, 1);
insert into book2author (book_id, author_id, sort_index) values (85, 18, 2);
insert into book2author (book_id, author_id, sort_index) values (85, 4, 3);
insert into book2author (book_id, author_id, sort_index) values (86, 29, 1);
insert into book2author (book_id, author_id, sort_index) values (86, 3, 2);
insert into book2author (book_id, author_id, sort_index) values (87, 23, 1);
insert into book2author (book_id, author_id, sort_index) values (87, 17, 2);
insert into book2author (book_id, author_id, sort_index) values (87, 18, 3);
insert into book2author (book_id, author_id, sort_index) values (88, 16, 1);
insert into book2author (book_id, author_id, sort_index) values (88, 17, 2);
insert into book2author (book_id, author_id, sort_index) values (89, 21, 1);
insert into book2author (book_id, author_id, sort_index) values (89, 9, 2);
insert into book2author (book_id, author_id, sort_index) values (89, 24, 3);
insert into book2author (book_id, author_id, sort_index) values (90, 11, 1);
insert into book2author (book_id, author_id, sort_index) values (90, 20, 2);
insert into book2author (book_id, author_id, sort_index) values (91, 12, 1);
insert into book2author (book_id, author_id, sort_index) values (91, 16, 2);
insert into book2author (book_id, author_id, sort_index) values (91, 31, 3);
insert into book2author (book_id, author_id, sort_index) values (92, 4, 1);
insert into book2author (book_id, author_id, sort_index) values (92, 25, 2);
insert into book2author (book_id, author_id, sort_index) values (93, 1, 1);
insert into book2author (book_id, author_id, sort_index) values (93, 7, 2);
insert into book2author (book_id, author_id, sort_index) values (93, 23, 3);
insert into book2author (book_id, author_id, sort_index) values (94, 2, 1);
insert into book2author (book_id, author_id, sort_index) values (94, 32, 2);
insert into book2author (book_id, author_id, sort_index) values (95, 2, 1);
insert into book2author (book_id, author_id, sort_index) values (95, 18, 2);
insert into book2author (book_id, author_id, sort_index) values (95, 28, 3);
insert into book2author (book_id, author_id, sort_index) values (96, 15, 1);
insert into book2author (book_id, author_id, sort_index) values (96, 25, 2);
insert into book2author (book_id, author_id, sort_index) values (97, 30, 1);
insert into book2author (book_id, author_id, sort_index) values (97, 31, 2);
insert into book2author (book_id, author_id, sort_index) values (97, 18, 3);
insert into book2author (book_id, author_id, sort_index) values (98, 1, 0);
insert into book2author (book_id, author_id, sort_index) values (99, 19, 0);
insert into book2author (book_id, author_id, sort_index) values (100, 5, 0);
-- book2author CONTENT - FINISH

-- book_review CONTENT - START
insert into book_review (book_id, user_id, time_, text_) values (1, 1, '2021-05-17 12:30:29', 'one review !!!'  );
insert into book_review (book_id, user_id, time_, text_) values (2, 2, '2022-06-18 22:33:33', 'two review !!!'  );
-- book_review CONTENT - FINISH

-- book_review_like CONTENT - START
insert into book_review_like (review_id, user_id, time_, value_) values ( 1, 2, '2021-07-19 02:35:35', 1 );
insert into book_review_like (review_id, user_id, time_, value_) values ( 2, 1, '2022-08-30 05:41:41', -1 );
-- book_review_like CONTENT - FINISH

-- genre CONTENT - START
insert into genre (parent_id, slug, name) VALUES ( NULL,  'zontrax', 'Zontrax');
insert into genre (parent_id, slug, name) VALUES ( NULL,  'wrapsafe', 'Wrapsafe');
insert into genre (parent_id, slug, name) VALUES ( NULL,  'zaam-dox', 'Zaam-dox');
insert into genre (parent_id, slug, name) VALUES ( NULL,  'alpha', 'Alpha');
insert into genre (parent_id, slug, name) VALUES ( NULL,  'y-find', 'Y-find');
insert into genre (parent_id, slug, name) VALUES ( NULL,  'flowdesc', 'Flowdesc');
insert into genre (parent_id, slug, name) VALUES ( NULL,  'blowdesc', 'Blowdesc');
insert into genre (parent_id, slug, name) VALUES ( NULL,  'lotlux', 'Lotlux');
insert into genre (parent_id, slug, name) VALUES ( NULL,  'regrant', 'Regrant');
insert into genre (parent_id, slug, name) VALUES ( NULL,  'veribet', 'Veribet');
insert into genre (parent_id, slug, name) VALUES ( 1,  'myrmetridactyla', 'Myrmecophaga tridactyla');
insert into genre (parent_id, slug, name) VALUES ( 1,  'senegalensis', 'Streptopelia senegalensis');
insert into genre (parent_id, slug, name) VALUES ( 1,  'ursinus', 'Vombatus ursinus');
insert into genre (parent_id, slug, name) VALUES ( 1,  'graspus', 'Graspus graspus');
insert into genre (parent_id, slug, name) VALUES ( 1,  'cristata', 'Hystrix cristata');
insert into genre (parent_id, slug, name) VALUES ( 1,  'novaehollandiae', 'Cereopsis novaehollandiae');
insert into genre (parent_id, slug, name) VALUES ( 1,  'mephitis', 'Mephitis mephitis');
insert into genre (parent_id, slug, name) VALUES ( 1,  'hoffmani', 'Choloepus hoffmani');
insert into genre (parent_id, slug, name) VALUES ( 1,  'unavailable', 'Unavailable');
insert into genre (parent_id, slug, name) VALUES ( 1,  'tristis', 'Acridotheres tristis');

insert into genre (parent_id, slug, name) VALUES ( 2,  'eugenii', 'Macropus eugenii');
insert into genre (parent_id, slug, name) VALUES ( 2,  'moschatus', 'Ovibos moschatus');
insert into genre (parent_id, slug, name) VALUES ( 2,  'murinus', 'Microcebus murinus');
insert into genre (parent_id, slug, name) VALUES ( 2,  'serval', 'Felis serval');
insert into genre (parent_id, slug, name) VALUES ( 2,  'cristatus', 'Proteles cristatus');
insert into genre (parent_id, slug, name) VALUES ( 2,  'paena', 'Certotrichas paena');
insert into genre (parent_id, slug, name) VALUES ( 2,  'curvirostre', 'Toxostoma curvirostre');
insert into genre (parent_id, slug, name) VALUES ( 2,  'fulvus', 'Lemur fulvus');
insert into genre (parent_id, slug, name) VALUES ( 2,  'elegans', 'Geochelone elegans');
insert into genre (parent_id, slug, name) VALUES ( 2,  'gularis', 'Paroaria gularis');

insert into genre (parent_id, slug, name) VALUES ( 3,  'indica', 'Ratufa indica');
insert into genre (parent_id, slug, name) VALUES ( 3,  'maculatus', 'Dasyurus maculatus');
insert into genre (parent_id, slug, name) VALUES ( 3,  'glareola', 'Tringa glareola');
insert into genre (parent_id, slug, name) VALUES ( 3,  'hermaphroditus', 'Paradoxurus hermaphroditus');
insert into genre (parent_id, slug, name) VALUES ( 3,  'thula', 'Egretta thula');
insert into genre (parent_id, slug, name) VALUES ( 3,  'cristata', 'Fulica cristata');
insert into genre (parent_id, slug, name) VALUES ( 3,  'vulpecula', 'Trichosurus vulpecula');
insert into genre (parent_id, slug, name) VALUES ( 3,  'robertsi', 'Kobus leche robertsi');
insert into genre (parent_id, slug, name) VALUES ( 3,  'glauca', 'Prionace glauca');
insert into genre (parent_id, slug, name) VALUES ( 3,  'giganteus', 'Cordylus giganteus');

insert into genre (parent_id, slug, name) VALUES ( 4,  'frontalis', 'Bos frontalis');
insert into genre (parent_id, slug, name) VALUES ( 4,  'antigone', 'Grus antigone');
insert into genre (parent_id, slug, name) VALUES ( 4,  'enviroment', 'Enviroment');
insert into genre (parent_id, slug, name) VALUES ( 4,  'eunectes', 'Eunectes sp.');
insert into genre (parent_id, slug, name) VALUES ( 4,  'tuberculifer', 'Myiarchus tuberculifer');
insert into genre (parent_id, slug, name) VALUES ( 4,  'americanus', 'Ursus americanus');
insert into genre (parent_id, slug, name) VALUES ( 4,  'concinnus', 'Cercatetus concinnus');
insert into genre (parent_id, slug, name) VALUES ( 4,  'popachka', 'Popa Zopa');
insert into genre (parent_id, slug, name) VALUES ( 4,  'orientalis', 'Ovis orientalis');
insert into genre (parent_id, slug, name) VALUES ( 4,  'mesomelas', 'Canis mesomelas');

insert into genre (parent_id, slug, name) VALUES ( 5,  'peregrinus', 'Falco peregrinus');
insert into genre (parent_id, slug, name) VALUES ( 5,  'anatinus', 'Ornithorhynchus anatinus');
insert into genre (parent_id, slug, name) VALUES ( 5,  'robustus', 'Macropus robustus');
insert into genre (parent_id, slug, name) VALUES ( 5,  'australis', 'Eubalaena australis');
insert into genre (parent_id, slug, name) VALUES ( 5,  'fulicarius', 'Phalaropus fulicarius');
insert into genre (parent_id, slug, name) VALUES ( 5,  'elegans', 'Geochelone elegans');
insert into genre (parent_id, slug, name) VALUES ( 5,  'hemionus', 'Odocoileus hemionus');
insert into genre (parent_id, slug, name) VALUES ( 5,  'carolina', 'Terrapene carolina');
insert into genre (parent_id, slug, name) VALUES ( 5,  'urophasianus', 'Centrocercus urophasianus');
insert into genre (parent_id, slug, name) VALUES ( 5,  'gambelii', 'Callipepla gambelii');

insert into genre (parent_id, slug, name) VALUES ( 6,  'entellus', 'Semnopithecus entellus');
insert into genre (parent_id, slug, name) VALUES ( 6,  'intermedius', 'Ploceus intermedius');
insert into genre (parent_id, slug, name) VALUES ( 6,  'africanus', 'Actophilornis africanus');
insert into genre (parent_id, slug, name) VALUES ( 6,  'mycteria', 'Ephippiorhynchus mycteria');
insert into genre (parent_id, slug, name) VALUES ( 6,  'rufus', 'Pteropus rufus');
insert into genre (parent_id, slug, name) VALUES ( 6,  'senegalensis', 'Ephipplorhynchus senegalensis');
insert into genre (parent_id, slug, name) VALUES ( 6,  'tristis', 'Acridotheres tristis');
insert into genre (parent_id, slug, name) VALUES ( 6,  'nigricans', 'Pycnonotus nigricans');
insert into genre (parent_id, slug, name) VALUES ( 6,  'albicollis', 'Corvus albicollis');
insert into genre (parent_id, slug, name) VALUES ( 6,  'vulpecula', 'Trichosurus vulpecula');

insert into genre (parent_id, slug, name) VALUES ( 7,  'novaehollandiae', 'Larus novaehollandiae');
insert into genre (parent_id, slug, name) VALUES ( 7,  'cinereus', 'Phascolarctos cinereus');
insert into genre (parent_id, slug, name) VALUES ( 7,  'oryx', 'Oryx gazella callotis');
insert into genre (parent_id, slug, name) VALUES ( 7,  'pipetca', 'Pipetca');
insert into genre (parent_id, slug, name) VALUES ( 7,  'leucocephala', 'Mycteria leucocephala');
insert into genre (parent_id, slug, name) VALUES ( 7,  'concolor', 'Lorythaixoides concolor');
insert into genre (parent_id, slug, name) VALUES ( 7,  'longicollis', 'Chelodina longicollis');
insert into genre (parent_id, slug, name) VALUES ( 7,  'lateralis', 'Spermophilus lateralis');
insert into genre (parent_id, slug, name) VALUES ( 7,  'vanaticus', 'Speothos vanaticus');
insert into genre (parent_id, slug, name) VALUES ( 7,  'cokii', 'Alcelaphus buselaphus cokii');

insert into genre (parent_id, slug, name) VALUES ( 8,  'arnee', 'Bubalus arnee');
insert into genre (parent_id, slug, name) VALUES ( 8,  'armatus', 'Anitibyx armatus');
insert into genre (parent_id, slug, name) VALUES ( 8,  'gelada', 'Theropithecus gelada');
insert into genre (parent_id, slug, name) VALUES ( 8,  'nigricans', 'Pycnonotus nigricans');
insert into genre (parent_id, slug, name) VALUES ( 8,  'graspus', 'Graspus graspus');
insert into genre (parent_id, slug, name) VALUES ( 8,  'javanicus', 'Herpestes javanicus');
insert into genre (parent_id, slug, name) VALUES ( 8,  'albifrons', 'Cebus albifrons');
insert into genre (parent_id, slug, name) VALUES ( 8,  'flavescens', 'Otaria flavescens');
insert into genre (parent_id, slug, name) VALUES ( 8,  'ferrugineus', 'Laniarius ferrugineus');
insert into genre (parent_id, slug, name) VALUES ( 8,  'tucanus', 'Ramphastos tucanus');

insert into genre (parent_id, slug, name) VALUES ( 9,  'leadbeateri', 'Bucorvus leadbeateri');
insert into genre (parent_id, slug, name) VALUES ( 9,  'robustus', 'Macropus robustus');
insert into genre (parent_id, slug, name) VALUES ( 9,  'truncatus', 'Tursiops truncatus');
insert into genre (parent_id, slug, name) VALUES ( 9,  'novemcinctus', 'Dasypus novemcinctus');
insert into genre (parent_id, slug, name) VALUES ( 9,  'delphis', 'Delphinus delphis');
insert into genre (parent_id, slug, name) VALUES ( 9,  'flaviventris', 'Marmota flaviventris');
insert into genre (parent_id, slug, name) VALUES ( 9,  'tristis', 'Acridotheres tristis');
insert into genre (parent_id, slug, name) VALUES ( 9,  'constrictor', 'Coluber constrictor');
insert into genre (parent_id, slug, name) VALUES ( 9,  'cochlearius', 'Cochlearius cochlearius');
insert into genre (parent_id, slug, name) VALUES ( 9,  'tenuirostris', 'Cacatua tenuirostris');

insert into genre (parent_id, slug, name) VALUES ( 10,  'strigoides', 'Podargus strigoides');
insert into genre (parent_id, slug, name) VALUES ( 10,  'cerastes', 'Crotalus cerastes');
insert into genre (parent_id, slug, name) VALUES ( 10,  'lybica', 'Felis silvestris lybica');
insert into genre (parent_id, slug, name) VALUES ( 10,  'aureus', 'Canis aureus');
insert into genre (parent_id, slug, name) VALUES ( 10,  'nubicus', 'Merops nubicus');
insert into genre (parent_id, slug, name) VALUES ( 10,  'robertsi', 'Kobus leche robertsi');
insert into genre (parent_id, slug, name) VALUES ( 10,  'rufogriseus', 'Macropus rufogriseus');
insert into genre (parent_id, slug, name) VALUES ( 10,  'virescens', 'Pseudoleistes virescens');
insert into genre (parent_id, slug, name) VALUES ( 10,  'leucoscepus', 'Francolinus leucoscepus');
insert into genre (parent_id, slug, name) VALUES ( 10,  'palumbus', 'Columba palumbus');
