insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (1, 'Zontrax', 147);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (2, 'Wrapsafe', 144);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (3, 'Zaam-Dox', 152);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (4, 'Alpha', 293);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (5, 'Y-find', 271);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (6, 'Flowdesk', 212);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (7, 'Flowdesk', 277);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (8, 'Lotlux', 235);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (9, 'Regrant', 112);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (10, 'Veribet', 146);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (11, 'Holdlamis', 165);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (12, 'Pannier', 108);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (13, 'Zamit', 209);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (14, 'Ventosanzap', 204);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (15, 'Prodder', 231);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (16, 'Bigtax', 278);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (17, 'Pannier', 256);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (18, 'Daltfresh', 207);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (19, 'Veribet', 207);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (20, 'Tres-Zap', 174);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (21, 'Holdlamis', 237);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (22, 'Aerified', 223);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (23, 'Transcof', 125);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (24, 'Temp', 183);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (25, 'Bytecard', 212);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (26, 'Andalax', 282);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (27, 'Ronstring', 108);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (28, 'Kanlam', 257);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (29, 'Flowdesk', 116);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (30, 'Alpha', 300);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (31, 'Latlux', 183);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (32, 'Bitchip', 142);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (33, 'Bitchip', 190);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (34, 'Job', 264);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (35, 'Tres-Zap', 182);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (36, 'Asoka', 272);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (37, 'It', 250);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (38, 'It', 256);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (39, 'Zoolab', 285);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (40, 'Stringtough', 216);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (41, 'Matsoft', 160);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (42, 'Stronghold', 105);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (43, 'Greenlam', 135);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (44, 'Viva', 256);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (45, 'Konklab', 170);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (46, 'Stringtough', 188);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (47, 'Alphazap', 228);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (48, 'Voltsillam', 112);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (49, 'Stim', 175);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (50, 'Daltfresh', 283);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (51, 'Holdlamis', 266);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (52, 'Andalax', 117);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (53, 'Matsoft', 206);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (54, 'Fintone', 102);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (55, 'Alpha', 258);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (56, 'Overhold', 174);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (57, 'Latlux', 132);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (58, 'Zathin', 277);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (59, 'Bitchip', 231);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (60, 'Alphazap', 129);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (61, 'Tempsoft', 153);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (62, 'Y-Solowarm', 185);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (63, 'Cardify', 281);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (64, 'Zaam-Dox', 129);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (65, 'Bytecard', 252);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (66, 'Zamit', 292);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (67, 'Kanlam', 137);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (68, 'Holdlamis', 194);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (69, 'Otcom', 138);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (70, 'Subin', 285);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (71, 'Sonsing', 247);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (72, 'Alpha', 163);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (73, 'Kanlam', 170);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (74, 'Cardguard', 268);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (75, 'Bitwolf', 218);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (76, 'Bigtax', 208);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (77, 'Zaam-Dox', 287);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (78, 'Rank', 278);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (79, 'Overhold', 154);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (80, 'Transcof', 140);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (81, 'Bytecard', 213);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (82, 'Tresom', 261);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (83, 'Greenlam', 125);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (84, 'Lotlux', 132);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (85, 'Stronghold', 247);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (86, 'Viva', 300);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (87, 'Andalax', 105);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (88, 'Pannier', 231);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (89, 'Tres-Zap', 195);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (90, 'Tempsoft', 251);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (91, 'Cardify', 163);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (92, 'Stim', 240);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (93, 'Trippledex', 297);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (94, 'Vagram', 111);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (95, 'Fix San', 208);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (96, 'Zoolab', 106);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (97, 'Latlux', 299);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (98, 'Zontrax', 189);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (99, 'Hatity', 278);
insert into tags_header_genres_page (id_tag_header_genres_page, tag_header_name_genres_page, tag_header_count_books) values (100, 'Stim', 115);


-- create EMPTY TAG
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (1, 'Myrmecophaga tridactyla', 330, 1);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (2, 'Streptopelia senegalensis', 410, 2);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (3, 'Vombatus ursinus', 447, 3);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (4, 'Graspus graspus', 472, 4);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (5, 'Hystrix cristata', 376, 5);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (6, 'Cereopsis novaehollandiae', 338, 1);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (7, 'Mephitis mephitis', 396, 1);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (8, 'Choloepus hoffmani', 400, 1);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (9, 'unavailable', 312, 2);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (10, 'Acridotheres tristis', 488, 2);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (11, 'Macropus eugenii', 392, 3);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (12, 'Ovibos moschatus', 367, 3);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (13, 'Microcebus murinus', 430, 4);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (14, 'Felis serval', 494, 4);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (15, 'Proteles cristatus', 433, 5);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (16, 'Certotrichas paena', 426, 5);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (17, 'Toxostoma curvirostre', 429, 5);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (18, 'Lemur fulvus', 349, 6);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (19, 'Geochelone elegans', 411, 6);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (20, 'Paroaria gularis', 438, 6);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (21, 'Ratufa indica', 373, 7);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (22, 'Dasyurus maculatus', 419, 7);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (23, 'Tringa glareola', 384, 77);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (24, 'Paradoxurus hermaphroditus', 420, 7);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (25, 'Egretta thula', 366, 8);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (26, 'Fulica cristata', 486, 8);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (27, 'Trichosurus vulpecula', 404, 9);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (28, 'Kobus leche robertsi', 427, 9);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (29, 'Prionace glauca', 415, 10);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (30, 'Cordylus giganteus', 425, 10);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (31, 'Bos frontalis', 388, 46);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (32, 'Grus antigone', 461, 87);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (33, 'unavailable', 470, 47);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (34, 'Eunectes sp.', 424, 31);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (35, 'Myiarchus tuberculifer', 372, 22);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (36, 'Ursus americanus', 313, 30);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (37, 'Cercatetus concinnus', 446, 86);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (38, 'unavailable', 309, 31);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (39, 'Ovis orientalis', 418, 50);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (40, 'Canis mesomelas', 344, 71);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (41, 'Falco peregrinus', 456, 99);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (42, 'Ornithorhynchus anatinus', 350, 45);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (43, 'Macropus robustus', 457, 8);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (44, 'Eubalaena australis', 479, 78);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (45, 'Phalaropus fulicarius', 479, 80);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (46, 'Geochelone elegans', 496, 11);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (47, 'Odocoileus hemionus', 425, 42);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (48, 'Terrapene carolina', 306, 93);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (49, 'Centrocercus urophasianus', 368, 42);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (50, 'Callipepla gambelii', 339, 12);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (51, 'Semnopithecus entellus', 308, 99);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (52, 'Ploceus intermedius', 390, 96);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (53, 'Actophilornis africanus', 498, 71);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (54, 'Ephippiorhynchus mycteria', 378, 65);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (55, 'Pteropus rufus', 494, 78);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (56, 'Ephipplorhynchus senegalensis', 442, 51);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (57, 'Acridotheres tristis', 485, 4);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (58, 'Pycnonotus nigricans', 343, 56);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (59, 'Corvus albicollis', 477, 49);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (60, 'Trichosurus vulpecula', 313, 20);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (61, 'Larus novaehollandiae', 429, 90);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (62, 'Phascolarctos cinereus', 355, 74);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (63, 'Oryx gazella callotis', 389, 10);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (64, 'unavailable', 392, 92);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (65, 'Mycteria leucocephala', 327, 32);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (66, 'Lorythaixoides concolor', 377, 65);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (67, 'Chelodina longicollis', 439, 56);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (68, 'Spermophilus lateralis', 494, 100);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (69, 'Speothos vanaticus', 429, 89);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (70, 'Alcelaphus buselaphus cokii', 372, 3);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (71, 'Bubalus arnee', 476, 78);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (72, 'Anitibyx armatus', 448, 46);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (73, 'Theropithecus gelada', 432, 76);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (74, 'Pycnonotus nigricans', 411, 56);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (75, 'Graspus graspus', 307, 1);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (76, 'Herpestes javanicus', 370, 70);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (77, 'Cebus albifrons', 338, 27);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (78, 'Otaria flavescens', 361, 65);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (79, 'Laniarius ferrugineus', 454, 25);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (80, 'Ramphastos tucanus', 323, 5);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (81, 'Bucorvus leadbeateri', 348, 42);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (82, 'Macropus robustus', 401, 96);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (83, 'Tursiops truncatus', 359, 81);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (84, 'Dasypus novemcinctus', 327, 9);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (85, 'Delphinus delphis', 359, 26);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (86, 'Marmota flaviventris', 357, 52);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (87, 'Acridotheres tristis', 429, 12);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (88, 'Coluber constrictor', 388, 5);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (89, 'Cochlearius cochlearius', 462, 42);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (90, 'Cacatua tenuirostris', 309, 45);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (91, 'Podargus strigoides', 334, 64);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (92, 'Crotalus cerastes', 424, 81);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (93, 'Felis silvestris lybica', 394, 72);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (94, 'Canis aureus', 367, 82);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (95, 'Merops nubicus', 387, 45);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (96, 'Kobus leche robertsi', 435, 2);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (97, 'Macropus rufogriseus', 435, 20);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (98, 'Pseudoleistes virescens', 413, 98);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (99, 'Francolinus leucoscepus', 370, 96);
insert into empty_tags_genres_page (id_empty_tag_genres_page, empty_tag_name_genres_page, empty_tag_count_books_genres_page, id_tag_header_genres_page) values (100, 'Columba palumbus', 432, 77);