insert into tags_main_page (tag_name_main_page) values ('modern literature');
insert into tags_main_page (tag_name_main_page) values ('classic literature');
insert into tags_main_page (tag_name_main_page) values ('foreign literature');
insert into tags_main_page (tag_name_main_page) values ('fantasy');
insert into tags_main_page (tag_name_main_page) values ('English literature');
insert into tags_main_page (tag_name_main_page) values ('Russian literature');
insert into tags_main_page (tag_name_main_page) values ('American literature');
insert into tags_main_page (tag_name_main_page) values ('fiction');
insert into tags_main_page (tag_name_main_page) values ('children ''s literature');
insert into tags_main_page (tag_name_main_page) values ('detective');
insert into tags_main_page (tag_name_main_page) values ('love');
insert into tags_main_page (tag_name_main_page) values ('Mystic');
insert into tags_main_page (tag_name_main_page) values ('humor');
insert into tags_main_page (tag_name_main_page) values ('Adventure');
insert into tags_main_page (tag_name_main_page) values ('French literature');
insert into tags_main_page (tag_name_main_page) values ('England');
insert into tags_main_page (tag_name_main_page) values ('fiction');
insert into tags_main_page (tag_name_main_page) values ('psychology');
insert into tags_main_page (tag_name_main_page) values ('philosophy');
insert into tags_main_page (tag_name_main_page) values ('filmed');
insert into tags_main_page (tag_name_main_page) values ('favorite');
insert into tags_main_page (tag_name_main_page) values ('dystopia');
insert into tags_main_page (tag_name_main_page) values ('books you should read before you die');
insert into tags_main_page (tag_name_main_page) values ('novel');
insert into tags_main_page (tag_name_main_page) values ('France');
insert into tags_main_page (tag_name_main_page) values ('give me two');
insert into tags_main_page (tag_name_main_page) values ('young adult');
insert into tags_main_page (tag_name_main_page) values ('war');
insert into tags_main_page (tag_name_main_page) values ('flashmob');
insert into tags_main_page (tag_name_main_page) values ('childhood');
insert into tags_main_page (tag_name_main_page) values ('life');
insert into tags_main_page (tag_name_main_page) values ('drama');
insert into tags_main_page (tag_name_main_page) values ('Russia');
insert into tags_main_page (tag_name_main_page) values ('book trip');
insert into tags_main_page (tag_name_main_page) values ('Soviet literature');
insert into tags_main_page (tag_name_main_page) values ('thriller');
insert into tags_main_page (tag_name_main_page) values ('America');
insert into tags_main_page (tag_name_main_page) values ('German literature');
insert into tags_main_page (tag_name_main_page) values ('vampires');
insert into tags_main_page (tag_name_main_page) values ('school program');
insert into tags_main_page (tag_name_main_page) values ('stories');
insert into tags_main_page (tag_name_main_page) values ('magic');
insert into tags_main_page (tag_name_main_page) values ('children');
insert into tags_main_page (tag_name_main_page) values ('Russian classics');
insert into tags_main_page (tag_name_main_page) values ('biography');
insert into tags_main_page (tag_name_main_page) values ('English');

