insert into tags (tag_name) values ('modern literature');
insert into tags (tag_name) values ('classic literature');
insert into tags (tag_name) values ('foreign literature');
insert into tags (tag_name) values ('fantasy');
insert into tags (tag_name) values ('English literature');
insert into tags (tag_name) values ('Russian literature');
insert into tags (tag_name) values ('American literature');
insert into tags (tag_name) values ('fiction');
insert into tags (tag_name) values ('children ''s literature');
insert into tags (tag_name) values ('detective');
insert into tags (tag_name) values ('love');
insert into tags (tag_name) values ('Mystic');
insert into tags (tag_name) values ('humor');
insert into tags (tag_name) values ('Adventure');
insert into tags (tag_name) values ('French literature');
insert into tags (tag_name) values ('England');
insert into tags (tag_name) values ('fiction');
insert into tags (tag_name) values ('psychology');
insert into tags (tag_name) values ('philosophy');
insert into tags (tag_name) values ('filmed');
insert into tags (tag_name) values ('favorite');
insert into tags (tag_name) values ('dystopia');
insert into tags (tag_name) values ('books you should read before you die');
insert into tags (tag_name) values ('novel');
insert into tags (tag_name) values ('France');
insert into tags (tag_name) values ('give me two');
insert into tags (tag_name) values ('young adult');
insert into tags (tag_name) values ('war');
insert into tags (tag_name) values ('flashmob');
insert into tags (tag_name) values ('childhood');
insert into tags (tag_name) values ('life');
insert into tags (tag_name) values ('drama');
insert into tags (tag_name) values ('Russia');
insert into tags (tag_name) values ('book trip');
insert into tags (tag_name) values ('Soviet literature');
insert into tags (tag_name) values ('thriller');
insert into tags (tag_name) values ('America');
insert into tags (tag_name) values ('German literature');
insert into tags (tag_name) values ('vampires');
insert into tags (tag_name) values ('school program');
insert into tags (tag_name) values ('stories');
insert into tags (tag_name) values ('magic');
insert into tags (tag_name) values ('children');
insert into tags (tag_name) values ('Russian classics');
insert into tags (tag_name) values ('biography');
insert into tags (tag_name) values ('English');

